default port tcp
tox-dev/tox-docker pull request #99
Opened 2021-05-20 09:37 UTC by chayim

2021-05-20 09:44 UTC, jugmac00 requested changes
Please have a look at the broken test suite.

2021-05-20 10:04 UTC, chayim commented on tox_docker/__init__.py
> +        host_port, container_port, protocol = re.findall(reg, port_line)[0]
Pushed again - sorry about that.

2021-05-20 11:09 UTC, jugmac00 commented
I removed myself as a reviewer as I neither use nor maintain this package. I just commented on the broken build to speed up the review process for the core maintainers.

2021-05-24 08:32 UTC, gaborbernat requested changes
We should also add some tests 👍

2021-05-24 08:32 UTC, gaborbernat commented on README.rst
> +    dockre default. See below for more on port mapping.
typo here

2021-05-24 18:47 UTC, dcrosta commented
I'm leaning towards not accepting this -- the inconvenience of having to type "tcp:" seems a small and infrequent price to pay for greater explicitness in the tox-docker config. Does anyone feel really strongly about this?

2021-05-24 20:24 UTC, chayim commented
Doing this is aligns tox-docker more closelt with docker. My bias is to
standardize on the behaviour of the tool with which I'm integrating. I
expected tox-docker to require port declarations to match the docker
syntax, it helps reduce the barrier to entry.

On Mon., May 24, 2021, 21:47 Dan Crosta, ***@***.***> wrote:

> I'm leaning towards not accepting this -- the inconvenience of having to
> type "tcp:" seems a small and infrequent price to pay for greater
> explicitness in the tox-docker config. Does anyone feel really strongly
> about this?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tox-dev/tox-docker/pull/99#issuecomment-847256449>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAKFVRTQPMRAWLQSCVT6EXTTPKNLXANCNFSM45GSZCWQ>
> .
>

2021-05-25 08:05 UTC, gaborbernat commented
I'm personally leaning towards @chayim here, but not strongly. Also note the main maintainer here is @dcrosta so ultimately it's up to his decision.

2021-05-27 05:36 UTC, chayim commented
> We should also add some tests

@gaborbernat Happy to add the tests and finish this off. But if @dcrosta doesn't want this behaviour then we should kill it off.

2021-06-22 07:20 UTC, chayim commented
Ping @dcrosta do you have a preference - prior to my writing the tests?

2021-12-09 14:43 UTC, chayim commented
Given the lack of answer - I assume we don't want this. Closing.

2021-12-09 14:43 UTC, closed without merging